console.log("                              --------------------------------                                          ")
console.log("                               THAKURDWARA PUBLIC SCHOOL                                            ")
console.log("                              --------------------------------                                          ")
console.log("#########    NAME  #####   CLASS  #########   ROLL NO.  #########  SUBJECT  #########  MARKS  ######### ")
console.log("                                            ^^^____^^^^                                                 ")
console.log("#########  Meenu Gupta  ##  12th   #########  20120065  #########  ENGLISH  #########  65/100  ######## ")
console.log("                                                                   HINDI               80/100           ")
console.log("                                                                   MATHS               90/100           ")
console.log("                                                                   SCIENCE             50/100           ")
console.log("                                                                   S.S.T               45/100           ")
console.log("                                            ^^^____^^^^                                                 ")
console.log("#########  Sonali Gupta  ##  12th   #########  20120066  #########  ENGLISH  #########  65/100  ######## ")
console.log("                                                                   HINDI               80/100           ")
console.log("                                                                   MATHS               90/100           ")
console.log("                                                                   SCIENCE             50/100           ")
console.log("                                                                   S.S.T               45/100           ")
console.log("                                            ^^^____^^^^                                                 ")
console.log("#########  Aashima Gupta  ##  12th   #########  20120065  #########  ENGLISH  #########  65/100  ######## ")
console.log("                                                                   HINDI               80/100           ")
console.log("                                                                   MATHS               90/100           ")
console.log("                                                                   SCIENCE             50/100           ")
console.log("                                                                   S.S.T               45/100           ")
